artifact_location: /Users/miftahhadiyannoor/Documents/logistics-rag/notebooks/runs/mlflow/481256391810599437
creation_time: 1770165276933
experiment_id: '481256391810599437'
last_update_time: 1770165276933
lifecycle_stage: active
name: /Shared/Ultralytics
