artifact_location: /Users/miftahhadiyannoor/Documents/logistics-rag/notebooks/runs/mlflow/0
creation_time: 1770118623055
experiment_id: '0'
last_update_time: 1770118623055
lifecycle_stage: active
name: Default
