-- Active: 1764687319910@@127.0.0.1@5432@supply_chain

CREATE SCHEMA IF NOT EXISTS shipment;
CREATE SCHEMA IF NOT EXISTS staging;
CREATE SCHEMA IF NOT EXISTS core;

DROP SCHEMA IF EXISTS core CASCADE;
CREATE SCHEMA IF NOT EXISTS inspection;
CREATE SCHEMA IF NOT EXISTS logistics;

CREATE SCHEMA IF NOT EXISTS analytics;

CREATE SCHEMA IF NOT EXISTS suppliers;
CREATE SCHEMA IF NOT EXISTS quality_inspection;
CREATE SCHEMA IF NOT EXISTS production_metrics;
CREATE SCHEMA IF NOT EXISTS sales_orders;
CREATE SCHEMA IF NOT EXISTS inventory_management;
CREATE SCHEMA IF NOT EXISTS raw;