artifact_location: /Users/miftahhadiyannoor/Documents/logistics-rag/notebooks/runs/mlflow/796512913123360958
creation_time: 1770118623060
experiment_id: '796512913123360958'
last_update_time: 1770118623060
lifecycle_stage: active
name: runs_container
